### ISSUE TITLE
Needs a readme

### ISSUE THREAD

**Issue by Julian-O** [kivy/templates#1]
It isn't clear at all what this repository is about.

Please update the readme to give context for what it does and who it is for.

**Comment by akshayaurora** [comment]
@Julian-O https://github.com/kivy/templates/commit/2b3d8accb0197768d59aebd879ee26a9e2a5c4f8

**Comment by Julian-O** [comment]
Thanks, @akshayaurora. 

I have been working through the Readmes (and other documentation) to make them consistent. I will add this to the bottom of my list.
